apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-audit
  namespace: ops-lab
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::919651863281:role/eks-lab-s3-audit-fargate
    eks.amazonaws.com/sts-regional-endpoints: "true"
automountServiceAccountToken: false
