apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: inventory-status
      namespace: ops-lab
    patch: |-
      - op: remove
        path: /spec/template/spec/topologySpreadConstraints
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests
        value:
          cpu: 250m
          memory: 128Mi
